INFO     root:conftest.py:13 开始计算
INFO     root:test_calc.py:88 计算1/1,预期结果为TypeError异常
INFO     root:conftest.py:16 结束运算